language: ruby
sudo: required
services:
  - docker

script:
  - docker build --target=lint .
  - docker build --target=build .

notifications:
  email:
    on_success: never
    on_failure: never
  pushover:
    on_success: change
    on_failure: always
    api_key:
      secure: diUwJTJM8+LfgSJDt5dba6iXlAH01/3bIOSj622mT4zNix91e2W00mleN0C1HaoQoOJ6JaMgQLUOqxmy1spqUbVs4sHpdTxcCaK9jF5Z/OslxRk7BGnLzaJYIKDUqoqPLWtkdFzrdrGAw5pHp3ZoQpNNxDn87R76b+43F2rPKpI=
    users:
      secure: QFycDr2Xncye5QsFFHJs7nSd2sek0ntb7d/PthDAGkpxrfW9ebqkvrpjGSBDQiytqTBKOiUOkKwAFFNz7csukCdZ1mdjgQNoKmTzIgQvakUjZUsLZC/rPGHMveRdoaCNgiUwxWIRUCxpAHtlOFiYEdeJFuO5ju4vgmYP0gF/hXY=
