sudo: required
language: ruby
services:
  - docker
cache:
  directories:
    - node_modules
env:
  global:
    - DOCKER_USERNAME=docwhat
    - secure: S2zWiSA4lh3F1qMBCBUZyF6Z+Slq1S1AxIBTQZ4dkUh6JODkGaerHHlFAAMBY4BQhZdLtJyAak9ToSdK8LxXu0EjaJyGQnUr5C3gRvwee8PuN2lyhMiO88j8uSq2pd93xbLw2g6gb3+We8WTy5N/Mk31s0jbzINlKShyBI7Teto=

script:
  - docker build --target=lint .
  - docker build --target=build .
  - env IMAGE_NAME=docwhat/docwhat:"$TRAVIS_BRANCH" hooks/build

deploy:
  provider: script
  script: hooks/docker_push_next
  on:
    branch: next

notifications:
  email:
    on_failure: never
    on_success: never
  pushover:
    api_key:
      secure: diUwJTJM8+LfgSJDt5dba6iXlAH01/3bIOSj622mT4zNix91e2W00mleN0C1HaoQoOJ6JaMgQLUOqxmy1spqUbVs4sHpdTxcCaK9jF5Z/OslxRk7BGnLzaJYIKDUqoqPLWtkdFzrdrGAw5pHp3ZoQpNNxDn87R76b+43F2rPKpI=
    on_failure: always
    on_success: change
    users:
      secure: QFycDr2Xncye5QsFFHJs7nSd2sek0ntb7d/PthDAGkpxrfW9ebqkvrpjGSBDQiytqTBKOiUOkKwAFFNz7csukCdZ1mdjgQNoKmTzIgQvakUjZUsLZC/rPGHMveRdoaCNgiUwxWIRUCxpAHtlOFiYEdeJFuO5ju4vgmYP0gF/hXY=
  webhooks: https://www.travisbuddy.com/
